sudo: required
services:
  - docker 

before_install:
  - docker build -t quannm244/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true quannm244/docker-react npm run test

deploy:
  edge: true
  provider: elasticbeanstalk
  region: "ap-east-1"
  app: "Docker1"
  env: "Docker1-env"
  bucket_name: "elasticbeanstalk-ap-east-1-510587096014"
  bucket_path: "Docker1"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
